### ISSUE TITLE
Plugin crashes

### ISSUE THREAD

**Issue by uncovery** [floored1585/SmartCart#2]
Error in logfile:

```
[03:42:49] [Server thread/ERROR]: Could not pass event VehicleEnterEvent to SmartCart v0.1.2
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-17fce80-25de1e6]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-17fce80-25de1e6]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) ~[spigot.jar:git-Spigot-17fce80-25de1e6]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) ~[spigot.jar:git-Spigot-17fce80-25de1e6]
at net.minecraft.server.v1_8_R3.Entity.mount(Entity.java:1569) ~[spigot.jar:git-Spigot-17fce80-25de1e6]
at net.minecraft.server.v1_8_R3.EntityLiving.mount(EntityLiving.java:1727) ~[spigot.jar:git-Spigot-17fce80-25de1e6]
at net.minecraft.server.v1_8_R3.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:402) ~[spigot.jar:git-Spigot-17fce80-25de1e6]
at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46) ~[spigot.jar:git-Spigot-17fce80-25de1e6]
at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) ~[spigot.jar:git-Spigot-17fce80-25de1e6]
at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188) ~[spigot.jar:git-Spigot-17fce80-25de1e6]
at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor$Task.get(AsynchronousExecutor.java:164) ~[spigot.jar:git-Spigot-17fce80-25de1e6]
at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:334) ~[spigot.jar:git-Spigot-17fce80-25de1e6]
at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[spigot.jar:git-Spigot-17fce80-25de1e6]
at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[spigot.jar:git-Spigot-17fce80-25de1e6]
at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:115) ~[spigot.jar:git-Spigot-17fce80-25de1e6]
at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97) ~[spigot.jar:git-Spigot-17fce80-25de1e6]
at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:125) ~[spigot.jar:git-Spigot-17fce80-25de1e6]
at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:89) ~[spigot.jar:git-Spigot-17fce80-25de1e6]
at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:567) ~[spigot.jar:git-Spigot-17fce80-25de1e6]
at org.bukkit.Location.getBlock(Location.java:87) ~[spigot.jar:git-Spigot-17fce80-25de1e6]
at net.f85.SmartCart.SmartCartVehicle.isOnRail(SmartCartVehicle.java:82) ~[?:?]
at net.f85.SmartCart.SmartCartListener.onVehicleEnter(SmartCartListener.java:80) ~[?:?]
at sun.reflect.GeneratedMethodAccessor379.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
```

This repeats endlessly.
I cannot figure out what causes it, exactly.

**Comment by uncovery** [comment]
See conversation here: http://uncovery.me/2015/05/28/minecart-trouble-removed-disabled/#comment-9607

**Comment by floored1585** [comment]
Rebuilt the JAR with 1.8.7 -- if that doesn't help I can add some additional (should be unnecessary though) checks to the onVehicleEnter or maybe rescue the EventException to allow whatever is breaking to fail silently without causing issues.
